### ISSUE TITLE
Change license to LGPL 2.1?

### ISSUE THREAD

**Issue by Nicholaswogan** [BoldingBruggeman/fortran-yaml#7]
I've built the `fortran-yaml-c` packaged, which uses some of the code in this repository: https://github.com/Nicholaswogan/fortran-yaml-c

Recently, Dom Heinzeller reached out to me asking me to change the license in `fortran-yaml-c` to something like LGPL 2.1 so that he could use the package in JEDI: https://www.jcsda.org/jcsda-project-jedi . I'm happy to make this change, but I think `fortran-yaml` would also need to change licenses to make all licenses compatible.

So, would you be willing to change the license to LGPL 2.1 or something similar?

**Comment by climbfuji** [comment]
Thanks @Nicholaswogan for initiating this. The issue with the GPLv2 and v3 licenses is that they are "strong leftcopy" licenses. In particular, they are incompatible with many licenses used by projects, such as the JCSDA Joint Effort for Data Assimilation Integration (JEDI), which is Apache 2.0 - you can’t use a GPLv3 project in Apache2 (the other way round would work though).

The easiest licenses to work with are the "permissive" licenses, e.g. Apache 2.0 and Adobe Creative Commons Zero. But LGPL v3 or v2.1 also works if those permissive licenses are not an option (albeit with restrictions - cannot directly integrate the code, but can link to it as a shared library).

This is all really complicated stuff :-) Thanks very much for your consideration!

**Comment by jornbr** [comment]
Thanks @Nicholaswogan - and @climbfuji, great to hear you're interested in using this work! It seems non-trivial to fully understand the intricacies and constraints when combining LGPL and Apache licensed software (complicated indeed!), but in any case, we are fine with switching to LGPL v2.1 (v2.1 seems preferable [to maintain compatibility with our other, mostly GPL v2 licensed software](https://www.gnu.org/licenses/gpl-faq.html#gpl-compat-matrix))

NB depending on your needs, you might benefit from the high level `yaml_settings` interface we added to fortran-yaml not too long ago. That's particularly well suited for reading configuration information from yaml files. Some examples [here](https://github.com/gotm-model/code/blob/master/src/gotm/gotm.F90#L234-L245). It's built on top of the original `yaml_types` and therefore presumably compatible with your fortran-yaml-c.

**Comment by Nicholaswogan** [comment]
Thanks @jornbr ! I'll have to take a look at yaml_settings and possibly port it over to fortran-yaml-c. Configuration files are my main use case for yaml.

I'm going to change the fortran-yaml-c license to LGPL v2.1 as well.

**Comment by climbfuji** [comment]
Yes thank you indeed @jornbr and @Nicholaswogan. LGPL v2.1 works. I really like the simple and clean implementation that you both put in place. Thanks for sharing your work.

**Comment by climbfuji** [comment]
I forgot to add, if you make it "LGPL v2.1 or later" then it's compatible with Apache 2 and LGPLv3 (the federal government uses the latter). If you make it "LGPL v2.1 only" then it is compatible with LGPLv3, but not Apache 2.

**Comment by climbfuji** [comment]
Thanks @Nicholaswogan for changing your license to lgpl v2.1. @jornbr Would it be possible for you to change yours, too? Thanks again for willing to do this.

**Comment by jornbr** [comment]
Done!

**Comment by climbfuji** [comment]
Great, thank you very much! This issue can be closed (I can't).
